### PR TITLE
It doesn't need to be pseudo

### PR DESCRIPTION
**Pull request by martinthomson**
Only randomness is necessary.  Also, cite RFC 4086.

### CODE REVIEW

**Review by FredericJacobs — APPROVED** [review]

**Review by chris-wood — COMMENTED** [review]
The added citation of RFC4086 is good, but I don't understand the intent behind the s/pseudorandom/random change. From a practical perspective, we need the bytes output from `random` to be indistinguishable from truly random bytes, which is why the pseudorandom property was noted. @martinthomson, @FredericJacobs, what am I missing?

**Comment by FredericJacobs** [comment]
The pseudo versus not pseudo debate is long one. Often divided between theory and practice folks. I don't care too much about the wording, even if in all implementations it's going to come from a PRNG

**Comment by chris-wood** [comment]
If the assumption behind this change is that "random bytes" could be instantiated using a PRNG (as should be, by definition), then I'm fine with this, but I'd just like some clarity on the opinionated choice of words here.

**Comment by martinthomson** [comment]
So the theory here is that a random number generator is not sufficient.  A *secure* random number generator suffices.  It is not necessary that it be pseudorandom.  That is, if you have a "true" random generator (whatever that is), then that would work too.

**Pull request merged**
