### PR TITLE
Add deterministic signature recommendation and API considerations.

### LINKED ISSUE #71: Clarify salting options
This issue is a summary of one discussed with the authors previously.

PSS implies a salt is included. This salt could be used to communicate information on the unblinded signed token. For some applications, this may not matter. For others, this could be used for a form of 'vote selling', where the salt is constructed in a non-random fashion but appears to the uninformed to be random. I'll refer to this as 'salt-signaling'.

Applications susceptible to salt-signaling may be better off requiring a zero-salt, which can be checked at verification time. This leaves only the token to communicate information with, which could be enforced by the application to be low-entropy.

Zero-salt reduces the security proof of PSS to an FDH, instead of binding it to the RSA proof, and therefor probably shouldn't be considered for every case.

With this in mind, should we prescribe two salting options in the spec? If we do, we'll need a concise description of the problem and what applications should consider when choosing a salting option.

### PR DESCRIPTION
**Pull request by chris-wood**
~Starting as a draft to iterate on API considerations. I started writing more about how the shape of a higher-level API might look, but it became too unwieldy. This seems like a good balance right now.~

cc smhendrickson

Closes #71.

### CODE REVIEW

**Comment by jedisct1** [comment]
This is great!

It is not invasive, yet addresses the sLen=0 case without cluttering the existing API with something that could be misused.

Maybe we should quickly explain what the use case for deterministic signatures is, though.

**Comment by chris-wood** [comment]
> Maybe we should quickly explain what the use case for deterministic signatures is, though.

I made an attempt to do this. Please feel free to recommend improvements or suggestions if you have them!

**Comment by jedisct1** [comment]
Looks good!

**Review by FredericJacobs — APPROVED** [review]
LGTM

**Pull request merged**
